"use server";

import { redirect } from "next/navigation";
import { createIncident, createSupportCase, updateIncident, updateSupportCase } from "@ax-finance/domain";
import { getCurrentUser } from "@/lib/session";
import { actionErrorMessage } from "@/lib/action-errors";

async function actor(){const user=await getCurrentUser();if(!user)redirect("/login");return user;}
const optional=(formData:FormData,name:string)=>String(formData.get(name)??"").trim()||undefined;
export async function createSupportCaseAction(formData:FormData){const user=await actor();try{await createSupportCase(user.id,{companyId:optional(formData,"companyId"),subject:String(formData.get("subject")??""),summary:String(formData.get("summary")??""),contactEmail:optional(formData,"contactEmail"),priority:String(formData.get("priority")??"NORMAL"),assignedToUserId:optional(formData,"assignedToUserId")});}catch(error){redirect(`/admin/suporte?erro=${encodeURIComponent(actionErrorMessage(error, "Falha ao criar chamado."))}`);}redirect("/admin/suporte?criado=chamado");}
export async function updateSupportCaseAction(caseId:string,formData:FormData){const user=await actor();try{await updateSupportCase(user.id,caseId,{status:String(formData.get("status")??""),priority:String(formData.get("priority")??""),assignedToUserId:optional(formData,"assignedToUserId"),resolution:optional(formData,"resolution")});}catch(error){redirect(`/admin/suporte?erro=${encodeURIComponent(actionErrorMessage(error, "Falha ao atualizar chamado."))}`);}redirect("/admin/suporte?atualizado=chamado");}
export async function createIncidentAction(formData:FormData){const user=await actor();try{await createIncident(user.id,{companyId:optional(formData,"companyId"),title:String(formData.get("title")??""),severity:String(formData.get("severity")??"SEV3"),publicMessage:String(formData.get("publicMessage")??""),internalSummary:optional(formData,"internalSummary")});}catch(error){redirect(`/admin/suporte?erro=${encodeURIComponent(actionErrorMessage(error, "Falha ao criar incidente."))}`);}redirect("/admin/suporte?criado=incidente");}
export async function updateIncidentAction(incidentId:string,formData:FormData){const user=await actor();try{await updateIncident(user.id,incidentId,{status:String(formData.get("status")??""),severity:String(formData.get("severity")??""),publicMessage:String(formData.get("publicMessage")??""),internalSummary:optional(formData,"internalSummary")});}catch(error){redirect(`/admin/suporte?erro=${encodeURIComponent(actionErrorMessage(error, "Falha ao atualizar incidente."))}`);}redirect("/admin/suporte?atualizado=incidente");}
