import { redirect } from "next/navigation";
import { getPlatformAdminAccess, listAdminSupport } from "@ax-finance/domain";
import { getCurrentUser } from "@/lib/session";
import { AdminNav } from "@/components/admin/admin-nav";
import { ActionModal } from "@/components/ui/action-modal";
import { createIncidentAction, createSupportCaseAction, updateIncidentAction, updateSupportCaseAction } from "./actions";

const CASE_STATUS:Record<string,string>={OPEN:"Aberto",IN_PROGRESS:"Em atendimento",WAITING_CUSTOMER:"Aguardando cliente",RESOLVED:"Resolvido",CLOSED:"Fechado"};
const PRIORITY:Record<string,string>={LOW:"Baixa",NORMAL:"Normal",HIGH:"Alta",URGENT:"Urgente"};
const INCIDENT_STATUS:Record<string,string>={INVESTIGATING:"Investigando",IDENTIFIED:"Identificado",MONITORING:"Monitorando",RESOLVED:"Resolvido"};

export default async function AdminSupportPage({searchParams}:{searchParams:{erro?:string;criado?:string;atualizado?:string}}){
  const user=await getCurrentUser();if(!user)redirect("/login");const access=await getPlatformAdminAccess(user.id);if(!access)redirect("/dashboard");
  const data=await listAdminSupport(user.id);const canWrite=access.role!=="ANALYST";
  const companyOptions=<><option value="">Plataforma inteira / sem empresa</option>{data.companies.map((company)=><option key={company.id} value={company.id}>{company.name}</option>)}</>;
  const adminOptions=<><option value="">Não atribuído</option>{data.admins.map((admin)=><option key={admin.userId} value={admin.userId}>{admin.user.name} · {admin.role}</option>)}</>;
  return <main className="wide"><div className="page-header"><div><h1>Suporte e incidentes</h1><p className="subtitle">Registro interno com responsável, prioridade, comunicação e resolução.</p></div>{canWrite?<div style={{display:"flex",gap:"0.75rem"}}><ActionModal triggerLabel="+ Chamado" title="Novo chamado"><form action={createSupportCaseAction}><label>Empresa</label><select name="companyId" defaultValue="">{companyOptions}</select><label>Assunto</label><input name="subject" required maxLength={200}/><label>Resumo</label><textarea name="summary" required maxLength={4000}/><label>Contato</label><input name="contactEmail" type="email" maxLength={200}/><label>Prioridade</label><select name="priority" defaultValue="NORMAL">{Object.entries(PRIORITY).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><label>Responsável</label><select name="assignedToUserId" defaultValue="">{adminOptions}</select><button type="submit">Criar chamado</button></form></ActionModal><ActionModal triggerLabel="+ Incidente" title="Novo incidente"><form action={createIncidentAction}><label>Empresa afetada</label><select name="companyId" defaultValue="">{companyOptions}</select><label>Título</label><input name="title" required maxLength={200}/><label>Severidade</label><select name="severity" defaultValue="SEV3"><option value="SEV1">SEV1 — crítico</option><option value="SEV2">SEV2 — alto</option><option value="SEV3">SEV3 — moderado</option><option value="SEV4">SEV4 — baixo</option></select><label>Mensagem pública</label><textarea name="publicMessage" required maxLength={2000}/><label>Resumo interno</label><textarea name="internalSummary" maxLength={4000}/><button type="submit">Abrir incidente</button></form></ActionModal></div>:null}</div><AdminNav/>
    {searchParams.erro?<p className="error">{searchParams.erro}</p>:null}{searchParams.criado?<p className="success-box">Registro criado e auditado.</p>:null}{searchParams.atualizado?<p className="success-box">Registro atualizado e auditado.</p>:null}
    <div className="card"><h1>Chamados</h1>{data.cases.length===0?<p className="muted">Nenhum chamado registrado.</p>:<table><thead><tr><th>Assunto</th><th>Empresa</th><th>Prioridade</th><th>Status</th><th>Responsável</th><th>Atualizado</th><th></th></tr></thead><tbody>{data.cases.map((item)=><tr key={item.id}><td><strong>{item.subject}</strong><br/><span className="muted">{item.summary}</span></td><td>{item.company?.name??"Plataforma"}</td><td>{PRIORITY[item.priority]}</td><td>{CASE_STATUS[item.status]}</td><td>{item.assignedTo?.name??"—"}</td><td>{item.updatedAt.toLocaleString("pt-BR")}</td><td>{canWrite?<ActionModal triggerLabel="Atualizar" title={`Chamado — ${item.subject}`}><form action={updateSupportCaseAction.bind(null,item.id)}><label>Status</label><select name="status" defaultValue={item.status}>{Object.entries(CASE_STATUS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><label>Prioridade</label><select name="priority" defaultValue={item.priority}>{Object.entries(PRIORITY).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><label>Responsável</label><select name="assignedToUserId" defaultValue={item.assignedToUserId??""}>{adminOptions}</select><label>Resolução/notas</label><textarea name="resolution" defaultValue={item.resolution??""} maxLength={4000}/><button type="submit">Salvar chamado</button></form></ActionModal>:null}</td></tr>)}</tbody></table>}</div>
    <div className="card"><h1>Incidentes</h1>{data.incidents.length===0?<p className="muted">Nenhum incidente registrado.</p>:<table><thead><tr><th>Incidente</th><th>Escopo</th><th>Severidade</th><th>Status</th><th>Início</th><th></th></tr></thead><tbody>{data.incidents.map((item)=><tr key={item.id}><td><strong>{item.title}</strong><br/><span className="muted">{item.publicMessage}</span></td><td>{item.company?.name??"Plataforma"}</td><td>{item.severity}</td><td>{INCIDENT_STATUS[item.status]}</td><td>{item.startedAt.toLocaleString("pt-BR")}</td><td>{canWrite?<ActionModal triggerLabel="Atualizar" title={`Incidente — ${item.title}`}><form action={updateIncidentAction.bind(null,item.id)}><label>Status</label><select name="status" defaultValue={item.status}>{Object.entries(INCIDENT_STATUS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><label>Severidade</label><select name="severity" defaultValue={item.severity}><option value="SEV1">SEV1</option><option value="SEV2">SEV2</option><option value="SEV3">SEV3</option><option value="SEV4">SEV4</option></select><label>Mensagem pública</label><textarea name="publicMessage" defaultValue={item.publicMessage} required maxLength={2000}/><label>Resumo interno</label><textarea name="internalSummary" defaultValue={item.internalSummary??""} maxLength={4000}/><button type="submit">Salvar incidente</button></form></ActionModal>:null}</td></tr>)}</tbody></table>}</div>
  </main>;
}
