export const EVENT_TYPE_LABEL: Record<string, string> = {
  SETTLEMENT_REGISTERED: "Baixa registrada",
  SETTLEMENT_REVERSED: "Baixa estornada",
  TITLE_CANCELLED: "Título cancelado",
  TRANSFER_CREATED: "Transferência criada",
  TRANSFER_REVERSED: "Transferência estornada",
  PERIOD_CLOSED: "Período fechado",
  PERIOD_REOPENED: "Período reaberto",
  TITLE_DELETED: "Título excluído",
  INSTALLMENT_PLAN_DELETED: "Parcelamento excluído",
  TITLE_SOFT_DELETED: "Título removido das telas",
  INSTALLMENT_PLAN_SOFT_DELETED: "Parcelamento removido das telas",
  BALANCE_ADJUSTMENT_CREATED: "Ajuste de saldo",
  BALANCE_ADJUSTMENT_REVERSED: "Ajuste de saldo estornado",
  COMPANY_INVITATION_CREATED: "Convite criado",
  COMPANY_INVITATION_ACCEPTED: "Convite aceito",
  COMPANY_INVITATION_REVOKED: "Convite revogado",
  COMPANY_MEMBER_ROLE_UPDATED: "Papel de usuário atualizado",
  COMPANY_MEMBER_ACCESS_UPDATED: "Escopo de acesso atualizado",
  COMPANY_OWNERSHIP_TRANSFERRED: "Propriedade transferida",
  COMPANY_MEMBER_REVOKED: "Acesso de usuário revogado",
  ATTACHMENT_ADDED: "Anexo adicionado",
  BANK_IMPORT_DELETED: "Importação de extrato removida",
  ATTACHMENT_DELETED: "Anexo removido",
  COST_CENTER_CREATED: "Centro de custo criado",
  COST_CENTER_ARCHIVED: "Centro de custo arquivado",
  COST_CENTER_UPDATED: "Centro de custo atualizado",
  TITLE_UPDATED: "Título atualizado",
  TITLE_DUPLICATED: "Título duplicado",
  TITLE_ALLOCATED: "Rateio atualizado",
  TITLE_ALLOCATION_CLEARED: "Rateio removido",
  SETTLEMENT_REFUND_REGISTERED: "Devolução/reembolso registrado",
  SETTLEMENT_REFUND_REVERSED: "Devolução/reembolso estornado",
  TITLE_BATCH_SETTLED: "Baixa em lote",
  TITLE_BATCH_CANCELLED: "Cancelamento em lote",
  TITLE_BATCH_CLASSIFIED: "Reclassificação em lote",
  FINANCIAL_ACCOUNT_UPDATED: "Conta atualizada",
  FINANCIAL_ACCOUNT_ARCHIVED: "Conta arquivada",
  FINANCIAL_ACCOUNT_REACTIVATED: "Conta reativada",
  COMPANY_LEDGER_RESET: "Lançamentos zerados (reset da conta)",
  BUDGET_SET: "Orçamento definido",
  BUDGET_COPIED: "Orçamentos copiados de outro mês",
  CREDIT_CARD_CREATED: "Cartão de crédito criado",
  CREDIT_CARD_UPDATED: "Cartão de crédito atualizado",
  CREDIT_CARD_ARCHIVED: "Cartão de crédito arquivado",
  CREDIT_CARD_DELETED: "Cartão de crédito excluído",
  CREDIT_CARD_REACTIVATED: "Cartão de crédito reativado",
  CREDIT_CARD_PURCHASE_CREATED: "Compra no cartão lançada",
  CREDIT_CARD_PURCHASE_UPDATED: "Compra no cartão atualizada",
  CREDIT_CARD_PURCHASE_CANCELED: "Compra no cartão cancelada",
  SUBSCRIPTION_BILLING_SYNCED: "Assinatura atualizada pela cobrança",
  SUBSCRIPTION_BILLING_CUSTOMER_LINKED: "Cliente de cobrança criado",
};
