export const EVENT_TYPE_LABEL: Record<string, string> = {
  SETTLEMENT_REGISTERED: "Baixa registrada",
  SETTLEMENT_REVERSED: "Baixa estornada",
  TITLE_CANCELLED: "Título cancelado",
  TRANSFER_CREATED: "Transferência criada",
  TRANSFER_REVERSED: "Transferência estornada",
  PERIOD_CLOSED: "Período fechado",
  PERIOD_REOPENED: "Período reaberto",
  TITLE_DELETED: "Título excluído",
  INSTALLMENT_PLAN_DELETED: "Parcelamento excluído",
  TITLE_SOFT_DELETED: "Título removido das telas",
  INSTALLMENT_PLAN_SOFT_DELETED: "Parcelamento removido das telas",
  BALANCE_ADJUSTMENT_CREATED: "Ajuste de saldo",
  BALANCE_ADJUSTMENT_REVERSED: "Ajuste de saldo estornado",
  COMPANY_INVITATION_CREATED: "Convite criado",
  COMPANY_INVITATION_ACCEPTED: "Convite aceito",
  COMPANY_INVITATION_REVOKED: "Convite revogado",
  COMPANY_MEMBER_ROLE_UPDATED: "Papel de usuário atualizado",
  COMPANY_MEMBER_ACCESS_UPDATED: "Escopo de acesso atualizado",
  COMPANY_OWNERSHIP_TRANSFERRED: "Propriedade transferida",
  COMPANY_MEMBER_REVOKED: "Acesso de usuário revogado",
  ATTACHMENT_ADDED: "Anexo adicionado",
  ATTACHMENT_DELETED: "Anexo removido",
  COST_CENTER_CREATED: "Centro de custo criado",
  COST_CENTER_ARCHIVED: "Centro de custo arquivado",
};
