import { redirect } from "next/navigation";
import { getPlatformAdminAccess, listAdminCompanies } from "@ax-finance/domain";
import { getCurrentUser } from "@/lib/session";
import { AdminNav } from "@/components/admin/admin-nav";
import { ActionModal } from "@/components/ui/action-modal";
import { updateSubscriptionAction } from "./actions";

const STATUS_LABEL:Record<string,string>={TRIAL:"Trial",ACTIVE:"Ativa",PAYMENT_PENDING:"Pagamento pendente",GRACE_PERIOD:"Carência",SUSPENDED:"Suspensa",CANCELLATION_SCHEDULED:"Cancelamento agendado",CANCELLED:"Cancelada"};
const dateValue=(value:Date|null|undefined)=>value?value.toISOString().slice(0,10):"";

export default async function AdminCompaniesPage({searchParams}:{searchParams:{busca?:string;assinatura?:string;erro?:string;atualizada?:string}}){
  const user=await getCurrentUser();if(!user)redirect("/login");const access=await getPlatformAdminAccess(user.id);if(!access)redirect("/dashboard");
  const subscriptionStatus=searchParams.assinatura&&searchParams.assinatura!=="ALL"?searchParams.assinatura:undefined;
  const companies=await listAdminCompanies(user.id,{search:searchParams.busca||undefined,subscriptionStatus});
  return <main className="wide"><div className="page-header"><div><h1>Empresas e assinaturas</h1><p className="subtitle">Até 200 resultados, ordenados pelas empresas mais recentes.</p></div></div><AdminNav/>
    {searchParams.erro?<p className="error">{searchParams.erro}</p>:null}{searchParams.atualizada?<p className="success-box">Assinatura atualizada e intervenção registrada na auditoria.</p>:null}
    <form method="get" className="card admin-filter-bar"><div><label htmlFor="admin-search">Empresa ou documento</label><input id="admin-search" name="busca" defaultValue={searchParams.busca??""}/></div><div><label htmlFor="admin-subscription">Assinatura</label><select id="admin-subscription" name="assinatura" defaultValue={searchParams.assinatura??"ALL"}><option value="ALL">Todas</option>{Object.entries(STATUS_LABEL).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div><button type="submit">Filtrar</button></form>
    <div className="card">{companies.length===0?<p className="muted">Nenhuma empresa encontrada.</p>:<table><thead><tr><th>Empresa</th><th>Proprietário</th><th>Assinatura</th><th>Trial/período</th><th>Uso</th><th>Suporte</th><th></th></tr></thead><tbody>{companies.map((company)=><tr key={company.id}><td><strong>{company.name}</strong><br/><span className="muted">{company.document||"Sem documento"} · {company.status}</span></td><td>{company.owner?<>{company.owner.name}<br/><span className="muted">{company.owner.email}</span></>:"—"}</td><td>{company.subscription?`${STATUS_LABEL[company.subscription.status]??company.subscription.status} · ${company.subscription.planCode}`:"Sem assinatura"}</td><td>{company.subscription?.trialEndsAt?`Trial: ${company.subscription.trialEndsAt.toLocaleDateString("pt-BR")}`:company.subscription?.currentPeriodEnd?`Até ${company.subscription.currentPeriodEnd.toLocaleDateString("pt-BR")}`:"—"}</td><td>{company._count.titles} títulos<br/><span className="muted">{company._count.memberships} usuários · {company._count.financialAccounts} contas</span></td><td>{company._count.supportCases} chamado(s)</td><td>{access.role==="SUPER_ADMIN"&&company.subscription?<ActionModal triggerLabel="Gerenciar" title={`Assinatura — ${company.name}`}><form action={updateSubscriptionAction.bind(null,company.id)}><label>Status</label><select name="status" defaultValue={company.subscription.status}>{Object.entries(STATUS_LABEL).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><label>Plano</label><input name="planCode" defaultValue={company.subscription.planCode} required maxLength={50}/><label>Fim do trial</label><input name="trialEndsAt" type="date" defaultValue={dateValue(company.subscription.trialEndsAt)}/><label>Fim do período</label><input name="currentPeriodEnd" type="date" defaultValue={dateValue(company.subscription.currentPeriodEnd)}/><label>Fim da carência</label><input name="graceEndsAt" type="date" defaultValue={dateValue(company.subscription.graceEndsAt)}/><label>Cancelamento efetivo</label><input name="cancellationEffectiveAt" type="date" defaultValue={dateValue(company.subscription.cancellationEffectiveAt)}/><label>Motivo da intervenção</label><input name="reason" required maxLength={500}/><button type="submit">Salvar assinatura</button></form></ActionModal>:null}</td></tr>)}</tbody></table>}</div>
  </main>;
}
