import { redirect } from "next/navigation";
import { getAdminOperations, getPlatformAdminAccess } from "@ax-finance/domain";
import { getCurrentUser } from "@/lib/session";
import { AdminNav } from "@/components/admin/admin-nav";
import { reprocessDeadLetterAction, reprocessImportJobAction, reprocessScheduledJobAction } from "./actions";
import { loginPathFor } from "@/lib/auth-return";

const dateTime=(value:Date|null)=>value?value.toLocaleString("pt-BR"):"—";
export default async function AdminOperationsPage({searchParams}:{searchParams:{erro?:string;reprocessado?:string}}){
  const user=await getCurrentUser();if(!user)redirect(loginPathFor("/admin/operacoes"));const access=await getPlatformAdminAccess(user.id);if(!access)redirect("/dashboard");
  const data=await getAdminOperations(user.id);const canReprocess=access.role==="SUPER_ADMIN"||access.role==="OPERATIONS";
  return <main className="wide"><div className="page-header"><div><h1>Diagnóstico e jobs</h1><p className="subtitle">Reprocessamento controlado, somente para falhas ou locks expirados.</p></div></div><AdminNav/>
    {searchParams.erro?<p className="error">{searchParams.erro}</p>:null}{searchParams.reprocessado?<p className="success-box">Item recolocado na fila. A intervenção foi auditada.</p>:null}
    <div className="admin-kpi-grid"><div className="card"><span className="muted">Banco</span><h1>{data.diagnostics.databaseLatencyMs} ms</h1></div><div className="card"><span className="muted">Outbox pendente</span><h1>{data.diagnostics.outbox.pending}</h1><p className="subtitle">{data.diagnostics.outbox.deadLetter} em dead letter</p></div><div className="card"><span className="muted">Jobs agendados</span><h1>{data.diagnostics.scheduledJobs.failing}</h1><p className="subtitle">{data.diagnostics.scheduledJobs.staleLocks} locks expirados</p></div><div className="card"><span className="muted">Importações</span><h1>{data.diagnostics.importJobs.failed}</h1><p className="subtitle">{data.diagnostics.importJobs.pending} pendentes</p></div></div>
    <div className="card"><h1>Jobs agendados com atenção</h1>{data.scheduledJobs.length===0?<p className="muted">Nenhum job com falha, atraso ou lock expirado.</p>:<table><thead><tr><th>Empresa</th><th>Tipo</th><th>Tentativas</th><th>Próxima execução</th><th>Erro seguro</th><th></th></tr></thead><tbody>{data.scheduledJobs.map((job)=><tr key={job.id}><td>{job.company.name}</td><td>{job.type}</td><td>{job.attempts}</td><td>{dateTime(job.nextRunAt)}</td><td>{job.lastError||"—"}</td><td>{canReprocess?<form action={reprocessScheduledJobAction.bind(null,job.id)} className="admin-reprocess-form"><input name="reason" placeholder="Motivo" required maxLength={500}/><button type="submit" className="secondary">Reprocessar</button></form>:null}</td></tr>)}</tbody></table>}</div>
    <div className="card"><h1>Importações com falha</h1>{data.importJobs.length===0?<p className="muted">Nenhuma importação exige intervenção.</p>:<table><thead><tr><th>Empresa</th><th>Arquivo</th><th>Status</th><th>Tentativas</th><th>Erro seguro</th><th></th></tr></thead><tbody>{data.importJobs.map((job)=><tr key={job.id}><td>{job.company.name}</td><td>{job.importBatch.fileName}</td><td>{job.status}</td><td>{job.attempts}</td><td>{job.lastError||"—"}</td><td>{canReprocess?<form action={reprocessImportJobAction.bind(null,job.id)} className="admin-reprocess-form"><input name="reason" placeholder="Motivo" required maxLength={500}/><button type="submit" className="secondary">Reprocessar</button></form>:null}</td></tr>)}</tbody></table>}</div>
    <div className="card"><h1>Outbox em dead letter</h1>{data.deadLetters.length===0?<p className="muted">Nenhum evento em dead letter.</p>:<table><thead><tr><th>Tipo</th><th>Tentativas</th><th>Atualizado</th><th>Erro seguro</th><th></th></tr></thead><tbody>{data.deadLetters.map((event)=><tr key={event.id}><td>{event.type}</td><td>{event.attempts}</td><td>{dateTime(event.updatedAt)}</td><td>{event.lastError||"—"}</td><td>{canReprocess&&event.canReprocess?<form action={reprocessDeadLetterAction.bind(null,event.id)} className="admin-reprocess-form"><input name="reason" placeholder="Motivo" required maxLength={500}/><button type="submit" className="secondary">Reprocessar</button></form>:<span className="muted">Payload indisponível</span>}</td></tr>)}</tbody></table>}</div>
    <div className="card"><h1>Intervenções recentes</h1>{data.auditEvents.length===0?<p className="muted">Nenhuma intervenção administrativa registrada.</p>:<table><thead><tr><th>Data</th><th>Administrador</th><th>Ação</th><th>Alvo</th><th>Motivo</th></tr></thead><tbody>{data.auditEvents.map((event)=><tr key={event.id}><td>{dateTime(event.createdAt)}</td><td>{event.actor.name}<br/><span className="muted">{event.actor.email}</span></td><td>{event.action}</td><td>{event.targetType}{event.targetId?` · ${event.targetId.slice(0,8)}`:""}</td><td>{event.summary}</td></tr>)}</tbody></table>}</div>
  </main>;
}
